apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-akki-local
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/akashjaiswal36/CD-GitOps.git
    targetRevision: main
    path: helm/devops-akki
    helm:
      valueFiles:
        - values-local.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
